=== V1527923840/jingdong/static/xml/demo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [
    <!ELEMENT bookstore(book*)>
    <!ELEMENT book (title,author,price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

    <!ATTLIST book
        publish(m) CDATA #REQUIRED
    >
    <!ELEMENT username "张三"> 
]>

=== V1527923840/jingdong/static/xml/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "demo.dtd">

<bookstore>
    <book publish="v">
        <title>金瓶梅</title>
        <author>张三</author>
        <price>￥5</price>
    </book>
    <book publish="v">
        <title>三国演义</title>
        <author>罗贯中</author>
        <price>￥6</price>
    </book>
    <book publish="v">
        <title>红楼梦</title>
        <author>曹雪芹</author>
        <price>￥6</price>
    </book>
    <book publish="v">
        <title>水浒传</title>
        <author>施耐庵</author>
        <price>￥6</price>
    </book>
    <book publish="v">
        <title>西游记</title>
        <author>吴承恩</author>
        <price>￥6</price>
    </book>
</bookstore>
